import type { FastifyInstance } from 'fastify'
import { z } from 'zod'
import archiver from 'archiver'
import { prisma } from '../lib/prisma.js'
import {
  parseGitHubUrl,
  getDefaultBranch,
  createBranch,
  commitFiles,
  createPullRequest,
} from '../services/tools/github.js'
import type { GeneratedFile, Message, AgentEvent } from '../types/index.js'

const pushGitHubSchema = z.object({
  githubToken: z.string().min(1),
  repoUrl: z.string().url(),
  branchName: z.string().min(1).default('devmind/generated'),
  prTitle: z.string().min(1).default('feat: add AI-generated code'),
  prBody: z.string().default('Generated by DevMind AI agents.'),
})

export async function exportRoutes(fastify: FastifyInstance) {
  fastify.addHook('onRequest', fastify.authenticate)

  // GET /api/projects/:projectId/sessions/:sessionId/export
  // Download all generated files as a ZIP archive
  fastify.get<{ Params: { projectId: string; sessionId: string } }>(
    '/:projectId/sessions/:sessionId/export',
    async (request, reply) => {
      const project = await prisma.project.findFirst({
        where: { id: request.params.projectId, userId: request.user.userId },
      })
      if (!project) return reply.code(404).send({ error: 'Project not found' })

      const session = await prisma.session.findFirst({
        where: { id: request.params.sessionId, projectId: project.id },
        include: { generatedFiles: true },
      })
      if (!session) return reply.code(404).send({ error: 'Session not found' })

      // Collect files from generatedFiles table + parse from messages
      const files: GeneratedFile[] = session.generatedFiles.map((f) => ({
        filename: f.filename,
        content: f.content,
        language: f.language,
      }))

      // Also extract from agent log tool_results
      const agentLog = session.agentLog as unknown as AgentEvent[]
      for (const event of agentLog) {
        if (event.type === 'tool_result' && event.tool !== 'github_context') {
          const result = event.toolResult
          if (Array.isArray(result)) {
            for (const item of result as GeneratedFile[]) {
              if (item.filename && item.content) {
                files.push(item)
              }
            }
          }
        }
      }

      // If no files found, extract from coder messages
      if (files.length === 0) {
        const messages = session.messages as unknown as Message[]
        for (const msg of messages) {
          if (msg.agentType === 'coder' && msg.role === 'assistant') {
            const filePattern = /\/\/\s*FILE:\s*(.+)\n([\s\S]*?)(?=\/\/\s*FILE:|$)/g
            let match
            while ((match = filePattern.exec(msg.content)) !== null) {
              const filename = match[1].trim()
              const content = match[2].trim()
              const ext = filename.split('.').pop()?.toLowerCase() ?? ''
              files.push({ filename, content, language: ext })
            }
          }
        }
      }

      if (files.length === 0) {
        return reply.code(404).send({ error: 'No generated files found in this session' })
      }

      reply.raw.writeHead(200, {
        'Content-Type': 'application/zip',
        'Content-Disposition': `attachment; filename="devmind-${session.id.slice(0, 8)}.zip"`,
      })

      const archive = archiver('zip', { zlib: { level: 9 } })
      archive.pipe(reply.raw)

      for (const file of files) {
        archive.append(file.content, { name: file.filename })
      }

      await archive.finalize()
    }
  )

  // POST /api/projects/:projectId/sessions/:sessionId/push-github
  // Create a branch, commit files, open a PR
  fastify.post<{ Params: { projectId: string; sessionId: string } }>(
    '/:projectId/sessions/:sessionId/push-github',
    async (request, reply) => {
      const body = pushGitHubSchema.safeParse(request.body)
      if (!body.success) {
        return reply.code(400).send({ error: body.error.flatten() })
      }

      const project = await prisma.project.findFirst({
        where: { id: request.params.projectId, userId: request.user.userId },
      })
      if (!project) return reply.code(404).send({ error: 'Project not found' })

      const session = await prisma.session.findFirst({
        where: { id: request.params.sessionId, projectId: project.id },
        include: { generatedFiles: true },
      })
      if (!session) return reply.code(404).send({ error: 'Session not found' })

      const parsed = parseGitHubUrl(body.data.repoUrl)
      if (!parsed) {
        return reply.code(400).send({ error: 'Invalid GitHub repository URL' })
      }

      const { owner, repo } = parsed
      const token = body.data.githubToken

      // Collect generated files
      const files: GeneratedFile[] = session.generatedFiles.map((f) => ({
        filename: f.filename,
        content: f.content,
        language: f.language,
      }))

      // Parse from coder messages if DB has none
      if (files.length === 0) {
        const messages = session.messages as unknown as Message[]
        for (const msg of messages) {
          if (msg.agentType === 'coder' && msg.role === 'assistant') {
            const filePattern = /\/\/\s*FILE:\s*(.+)\n([\s\S]*?)(?=\/\/\s*FILE:|$)/g
            let match
            while ((match = filePattern.exec(msg.content)) !== null) {
              files.push({ filename: match[1].trim(), content: match[2].trim(), language: '' })
            }
          }
        }
      }

      if (files.length === 0) {
        return reply.code(404).send({ error: 'No generated files to push' })
      }

      try {
        const defaultBranch = await getDefaultBranch(token, owner, repo)

        const branchName = `${body.data.branchName}-${Date.now()}`
        await createBranch(token, owner, repo, branchName, defaultBranch.sha)

        await commitFiles(
          token,
          owner,
          repo,
          branchName,
          files.map((f) => ({ path: f.filename, content: f.content })),
          `feat: add DevMind generated code for "${project.title}"`
        )

        const prUrl = await createPullRequest(
          token,
          owner,
          repo,
          branchName,
          defaultBranch.name,
          body.data.prTitle,
          body.data.prBody
        )

        return reply.send({ success: true, prUrl, branch: branchName, filesCount: files.length })
      } catch (err) {
        const message = err instanceof Error ? err.message : 'GitHub operation failed'
        return reply.code(500).send({ error: message })
      }
    }
  )
}
